# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.marketplace_api import MarketplaceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMarketplaceApi(unittest.TestCase):
    """MarketplaceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.marketplace_api.MarketplaceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_order_by_buyer(self):
        """Test case for accept_order_by_buyer

        Accepts a pending order by buyer.  # noqa: E501
        """
        pass

    def test_accept_order_by_seller(self):
        """Test case for accept_order_by_seller

        Accepts a pending order by seller.  # noqa: E501
        """
        pass

    def test_add_item_to_shopping_cart(self):
        """Test case for add_item_to_shopping_cart

        Adds the given webshop ad to the corresponding shopping cart.  # noqa: E501
        """
        pass

    def test_adjust_and_get_shopping_cart_details(self):
        """Test case for adjust_and_get_shopping_cart_details

        Adjusts a shopping cart items, returning its details.  # noqa: E501
        """
        pass

    def test_checkout_shopping_cart(self):
        """Test case for checkout_shopping_cart

        Checks out a shopping cart.  # noqa: E501
        """
        pass

    def test_create_ad(self):
        """Test case for create_ad

        Creates a new advertisement for the given user.  # noqa: E501
        """
        pass

    def test_create_ad_question(self):
        """Test case for create_ad_question

        Creates a new advertisement question.  # noqa: E501
        """
        pass

    def test_delete_ad(self):
        """Test case for delete_ad

        Removes an advertisement.  # noqa: E501
        """
        pass

    def test_delete_ad_question(self):
        """Test case for delete_ad_question

        Removes an advertisement question.  # noqa: E501
        """
        pass

    def test_get_ad_data_for_edit(self):
        """Test case for get_ad_data_for_edit

        Returns configuration data for editing an advertisement.  # noqa: E501
        """
        pass

    def test_get_ad_data_for_new(self):
        """Test case for get_ad_data_for_new

        Returns configuration data for creating a new advertisement for a user and kind.   # noqa: E501
        """
        pass

    def test_get_ad_data_for_search(self):
        """Test case for get_ad_data_for_search

        Returns configuration data for searching advertisements.  # noqa: E501
        """
        pass

    def test_get_ad_question(self):
        """Test case for get_ad_question

        Returns details of an advertisement question.  # noqa: E501
        """
        pass

    def test_get_data_for_set_delivery_method(self):
        """Test case for get_data_for_set_delivery_method

        Returns configuration data to set delivery method data by seller.  # noqa: E501
        """
        pass

    def test_get_order_data_for_accept_by_buyer(self):
        """Test case for get_order_data_for_accept_by_buyer

        Returns configuration data for accept an order by buyer.  # noqa: E501
        """
        pass

    def test_get_shopping_cart_data_for_checkout(self):
        """Test case for get_shopping_cart_data_for_checkout

        Returns configuration data for check-out a shopping cart.  # noqa: E501
        """
        pass

    def test_get_shopping_cart_details(self):
        """Test case for get_shopping_cart_details

        Returns details of a shopping cart.  # noqa: E501
        """
        pass

    def test_get_shopping_carts(self):
        """Test case for get_shopping_carts

        Returns the shopping carts list.  # noqa: E501
        """
        pass

    def test_get_user_ads_data_for_search(self):
        """Test case for get_user_ads_data_for_search

        Returns configuration data for searching advertisements of a user.  # noqa: E501
        """
        pass

    def test_modify_item_quantity_on_shopping_cart(self):
        """Test case for modify_item_quantity_on_shopping_cart

        Modifies the corresponding cart with the new quantity for the given webshop ad.   # noqa: E501
        """
        pass

    def test_reject_order(self):
        """Test case for reject_order

        Rejects a pending order.  # noqa: E501
        """
        pass

    def test_remove_item_from_shopping_cart(self):
        """Test case for remove_item_from_shopping_cart

        Removes the given webshop ad from the corresponding shopping cart.  # noqa: E501
        """
        pass

    def test_remove_shopping_cart(self):
        """Test case for remove_shopping_cart

        Removes a shopping cart.  # noqa: E501
        """
        pass

    def test_search_ads(self):
        """Test case for search_ads

        Searches for advertisements.  # noqa: E501
        """
        pass

    def test_search_user_ads(self):
        """Test case for search_user_ads

        Searches for advertisements of a specific user.  # noqa: E501
        """
        pass

    def test_search_user_orders(self):
        """Test case for search_user_orders

        Searches for orders of a specific user.  # noqa: E501
        """
        pass

    def test_set_delivery_method(self):
        """Test case for set_delivery_method

        Sets delivery method data by seller.  # noqa: E501
        """
        pass

    def test_update_ad(self):
        """Test case for update_ad

        Updates an existing advertisement.  # noqa: E501
        """
        pass

    def test_view_ad(self):
        """Test case for view_ad

        Returns details of an advertisement.  # noqa: E501
        """
        pass

    def test_view_order(self):
        """Test case for view_order

        Returns details of an order.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
