# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.operators_api import OperatorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOperatorsApi(unittest.TestCase):
    """OperatorsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.operators_api.OperatorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_general_operators_data_for_search(self):
        """Test case for get_general_operators_data_for_search

        Get configuration data for searching operators of any managed user  # noqa: E501
        """
        pass

    def test_get_user_operators_data_for_search(self):
        """Test case for get_user_operators_data_for_search

        Get configuration data for searching operators of the given user  # noqa: E501
        """
        pass

    def test_search_general_operators(self):
        """Test case for search_general_operators

        Search the visible operators (of any managed user)  # noqa: E501
        """
        pass

    def test_search_user_operators(self):
        """Test case for search_user_operators

        Search the operators of a given user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
