# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.address_edit_with_id import AddressEditWithId  # noqa: E501
from swagger_client.rest import ApiException


class TestAddressEditWithId(unittest.TestCase):
    """AddressEditWithId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressEditWithId(self):
        """Test AddressEditWithId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.address_edit_with_id.AddressEditWithId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
