# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.bad_request_error_code import BadRequestErrorCode  # noqa: E501
from swagger_client.rest import ApiException


class TestBadRequestErrorCode(unittest.TestCase):
    """BadRequestErrorCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBadRequestErrorCode(self):
        """Test BadRequestErrorCode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bad_request_error_code.BadRequestErrorCode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
