# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accounts_api import AccountsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.accounts_api.AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account_balance_history(self):
        """Test case for get_account_balance_history

        Returns the account balances over time  # noqa: E501
        """
        pass

    def test_get_account_history_data_by_owner_and_type(self):
        """Test case for get_account_history_data_by_owner_and_type

        Returns data for searching an account history by owner and type  # noqa: E501
        """
        pass

    def test_get_account_status_by_owner_and_type(self):
        """Test case for get_account_status_by_owner_and_type

        Returns the status of an account by owner and type  # noqa: E501
        """
        pass

    def test_get_user_balances_data(self):
        """Test case for get_user_balances_data

        Returns data for searching users together with their balances  # noqa: E501
        """
        pass

    def test_get_user_balances_summary(self):
        """Test case for get_user_balances_summary

        Returns summarized information for the user balances search  # noqa: E501
        """
        pass

    def test_list_accounts_by_owner(self):
        """Test case for list_accounts_by_owner

        Lists accounts of the given owner with their statuses  # noqa: E501
        """
        pass

    def test_search_account_history(self):
        """Test case for search_account_history

        Search an account history  # noqa: E501
        """
        pass

    def test_search_users_with_balances(self):
        """Test case for search_users_with_balances

        Searches for users together with balance information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
