# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.payment_requests_api import PaymentRequestsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPaymentRequestsApi(unittest.TestCase):
    """PaymentRequestsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.payment_requests_api.PaymentRequestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_payment_request(self):
        """Test case for accept_payment_request

        Accepts a payment request.  # noqa: E501
        """
        pass

    def test_cancel_payment_request(self):
        """Test case for cancel_payment_request

        Cancels a payment request.  # noqa: E501
        """
        pass

    def test_change_payment_request_expiration_date(self):
        """Test case for change_payment_request_expiration_date

        Changes the payment request expiration.  # noqa: E501
        """
        pass

    def test_data_for_send_payment_request(self):
        """Test case for data_for_send_payment_request

        Returns configuration data for sending a payment request  # noqa: E501
        """
        pass

    def test_preview_payment_request(self):
        """Test case for preview_payment_request

        Previews the payment performed when accepting the given payment request.   # noqa: E501
        """
        pass

    def test_reject_payment_request(self):
        """Test case for reject_payment_request

        Rejects a payment request.  # noqa: E501
        """
        pass

    def test_reschedule_payment_request(self):
        """Test case for reschedule_payment_request

        Reschedules a payment request.  # noqa: E501
        """
        pass

    def test_send_payment_request(self):
        """Test case for send_payment_request

        Sends a payment request from the given owner  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
