# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.records_api import RecordsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRecordsApi(unittest.TestCase):
    """RecordsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.records_api.RecordsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_record(self):
        """Test case for create_record

        Creates a new record for the given owner and type  # noqa: E501
        """
        pass

    def test_delete_record(self):
        """Test case for delete_record

        Removes a record  # noqa: E501
        """
        pass

    def test_get_record_data_for_edit(self):
        """Test case for get_record_data_for_edit

        Returns data to edit an existing record  # noqa: E501
        """
        pass

    def test_get_record_data_for_general_search(self):
        """Test case for get_record_data_for_general_search

        Returns data for searching records of a type over any owner  # noqa: E501
        """
        pass

    def test_get_record_data_for_new(self):
        """Test case for get_record_data_for_new

        Returns data to create a new record  # noqa: E501
        """
        pass

    def test_get_record_data_for_owner_search(self):
        """Test case for get_record_data_for_owner_search

        Returns data for searching records of a specific type and owner  # noqa: E501
        """
        pass

    def test_get_record_data_for_shared_search(self):
        """Test case for get_record_data_for_shared_search

        Returns data for searching records with shared fields  # noqa: E501
        """
        pass

    def test_get_record_type_by_owner(self):
        """Test case for get_record_type_by_owner

        Returns a single record type over a user or system  # noqa: E501
        """
        pass

    def test_list_record_types_by_owner(self):
        """Test case for list_record_types_by_owner

        Lists the record types over a user or system  # noqa: E501
        """
        pass

    def test_list_record_types_for_general_search(self):
        """Test case for list_record_types_for_general_search

        Lists the record types for general search  # noqa: E501
        """
        pass

    def test_search_general_records(self):
        """Test case for search_general_records

        Searches for records of a specific type over any owner  # noqa: E501
        """
        pass

    def test_search_owner_records(self):
        """Test case for search_owner_records

        Searches for records of a specific type and owner  # noqa: E501
        """
        pass

    def test_search_shared_records(self):
        """Test case for search_shared_records

        Searches for records with shared fields  # noqa: E501
        """
        pass

    def test_update_record(self):
        """Test case for update_record

        Updates an existing record  # noqa: E501
        """
        pass

    def test_view_record(self):
        """Test case for view_record

        Returns details of a specific record  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
