# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.agreement_content import AgreementContent  # noqa: E501
from swagger_client.rest import ApiException


class TestAgreementContent(unittest.TestCase):
    """AgreementContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgreementContent(self):
        """Test AgreementContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.agreement_content.AgreementContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
