# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class AccountWithOwner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'kind': 'AccountKind',
        'user': 'User'
    }

    attribute_map = {
        'kind': 'kind',
        'user': 'user'
    }

    def __init__(self, kind=None, user=None, _configuration=None):  # noqa: E501
        """AccountWithOwner - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._kind = None
        self._user = None
        self.discriminator = None

        if kind is not None:
            self.kind = kind
        if user is not None:
            self.user = user

    @property
    def kind(self):
        """Gets the kind of this AccountWithOwner.  # noqa: E501

        Indicates whether an account belongs to system or user Possible values are: * system: System account, there is only one account per type in the system. Managed only by administrators * user: User account, there is one account of this type per user.   # noqa: E501

        :return: The kind of this AccountWithOwner.  # noqa: E501
        :rtype: AccountKind
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this AccountWithOwner.

        Indicates whether an account belongs to system or user Possible values are: * system: System account, there is only one account per type in the system. Managed only by administrators * user: User account, there is one account of this type per user.   # noqa: E501

        :param kind: The kind of this AccountWithOwner.  # noqa: E501
        :type: AccountKind
        """

        self._kind = kind

    @property
    def user(self):
        """Gets the user of this AccountWithOwner.  # noqa: E501

        Only returned if `kind` is `user`. Is a reference to the owner user.   # noqa: E501

        :return: The user of this AccountWithOwner.  # noqa: E501
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this AccountWithOwner.

        Only returned if `kind` is `user`. Is a reference to the owner user.   # noqa: E501

        :param user: The user of this AccountWithOwner.  # noqa: E501
        :type: User
        """

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountWithOwner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountWithOwner):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AccountWithOwner):
            return True

        return self.to_dict() != other.to_dict()
