# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class AdDataForSearch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'groups': 'list[Group]',
        'default_groups': 'list[str]',
        'query': 'AdQueryFilters'
    }

    attribute_map = {
        'groups': 'groups',
        'default_groups': 'defaultGroups',
        'query': 'query'
    }

    def __init__(self, groups=None, default_groups=None, query=None, _configuration=None):  # noqa: E501
        """AdDataForSearch - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._groups = None
        self._default_groups = None
        self._query = None
        self.discriminator = None

        if groups is not None:
            self.groups = groups
        if default_groups is not None:
            self.default_groups = default_groups
        if query is not None:
            self.query = query

    @property
    def groups(self):
        """Gets the groups of this AdDataForSearch.  # noqa: E501

        The groups the authenticated user can use to filter users. Admins can always filter by groups, while users depend on a permission, which can be to only view group sets, only groups or none.   # noqa: E501

        :return: The groups of this AdDataForSearch.  # noqa: E501
        :rtype: list[Group]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this AdDataForSearch.

        The groups the authenticated user can use to filter users. Admins can always filter by groups, while users depend on a permission, which can be to only view group sets, only groups or none.   # noqa: E501

        :param groups: The groups of this AdDataForSearch.  # noqa: E501
        :type: list[Group]
        """

        self._groups = groups

    @property
    def default_groups(self):
        """Gets the default_groups of this AdDataForSearch.  # noqa: E501

        The internal names (or ids, if missing) of the groups which should be presented by default on user search   # noqa: E501

        :return: The default_groups of this AdDataForSearch.  # noqa: E501
        :rtype: list[str]
        """
        return self._default_groups

    @default_groups.setter
    def default_groups(self, default_groups):
        """Sets the default_groups of this AdDataForSearch.

        The internal names (or ids, if missing) of the groups which should be presented by default on user search   # noqa: E501

        :param default_groups: The default_groups of this AdDataForSearch.  # noqa: E501
        :type: list[str]
        """

        self._default_groups = default_groups

    @property
    def query(self):
        """Gets the query of this AdDataForSearch.  # noqa: E501

        Default query filters to search advertisements   # noqa: E501

        :return: The query of this AdDataForSearch.  # noqa: E501
        :rtype: AdQueryFilters
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this AdDataForSearch.

        Default query filters to search advertisements   # noqa: E501

        :param query: The query of this AdDataForSearch.  # noqa: E501
        :type: AdQueryFilters
        """

        self._query = query

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdDataForSearch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdDataForSearch):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdDataForSearch):
            return True

        return self.to_dict() != other.to_dict()
