# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class AdQueryFilters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'owner': 'str',
        'broker': 'str',
        'groups': 'list[str]',
        'return_editable': 'bool'
    }

    attribute_map = {
        'owner': 'owner',
        'broker': 'broker',
        'groups': 'groups',
        'return_editable': 'returnEditable'
    }

    def __init__(self, owner=None, broker=None, groups=None, return_editable=None, _configuration=None):  # noqa: E501
        """AdQueryFilters - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._owner = None
        self._broker = None
        self._groups = None
        self._return_editable = None
        self.discriminator = None

        if owner is not None:
            self.owner = owner
        if broker is not None:
            self.broker = broker
        if groups is not None:
            self.groups = groups
        if return_editable is not None:
            self.return_editable = return_editable

    @property
    def owner(self):
        """Gets the owner of this AdQueryFilters.  # noqa: E501

        Either id or an identification, such as login name, e-mail, etc, for the advertisement owner. The allowed identification methods are those the authenticated user can use on keywords search.   # noqa: E501

        :return: The owner of this AdQueryFilters.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this AdQueryFilters.

        Either id or an identification, such as login name, e-mail, etc, for the advertisement owner. The allowed identification methods are those the authenticated user can use on keywords search.   # noqa: E501

        :param owner: The owner of this AdQueryFilters.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def broker(self):
        """Gets the broker of this AdQueryFilters.  # noqa: E501

        Either id or an identification, such as login name, e-mail, etc, for the broker of the advertisement owner. The allowed identification methods are those the authenticated user can use on keywords search.   # noqa: E501

        :return: The broker of this AdQueryFilters.  # noqa: E501
        :rtype: str
        """
        return self._broker

    @broker.setter
    def broker(self, broker):
        """Sets the broker of this AdQueryFilters.

        Either id or an identification, such as login name, e-mail, etc, for the broker of the advertisement owner. The allowed identification methods are those the authenticated user can use on keywords search.   # noqa: E501

        :param broker: The broker of this AdQueryFilters.  # noqa: E501
        :type: str
        """

        self._broker = broker

    @property
    def groups(self):
        """Gets the groups of this AdQueryFilters.  # noqa: E501

        Array of either id or internal names of user groups the advertisement owner must belong to   # noqa: E501

        :return: The groups of this AdQueryFilters.  # noqa: E501
        :rtype: list[str]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this AdQueryFilters.

        Array of either id or internal names of user groups the advertisement owner must belong to   # noqa: E501

        :param groups: The groups of this AdQueryFilters.  # noqa: E501
        :type: list[str]
        """

        self._groups = groups

    @property
    def return_editable(self):
        """Gets the return_editable of this AdQueryFilters.  # noqa: E501

        Whether to return the editable property. Passing `true` will impact the performance a bit, as for each returned advertisement some statuses and permissions need to be checked.   # noqa: E501

        :return: The return_editable of this AdQueryFilters.  # noqa: E501
        :rtype: bool
        """
        return self._return_editable

    @return_editable.setter
    def return_editable(self, return_editable):
        """Sets the return_editable of this AdQueryFilters.

        Whether to return the editable property. Passing `true` will impact the performance a bit, as for each returned advertisement some statuses and permissions need to be checked.   # noqa: E501

        :param return_editable: The return_editable of this AdQueryFilters.  # noqa: E501
        :type: bool
        """

        self._return_editable = return_editable

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdQueryFilters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdQueryFilters):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdQueryFilters):
            return True

        return self.to_dict() != other.to_dict()
