# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class BaseUserDataForSearch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'allow_keywords': 'bool',
        'fields_in_search': 'list[str]',
        'address_fields_in_search': 'list[AddressQueryFieldEnum]',
        'basic_fields': 'list[BasicProfileFieldInput]',
        'custom_fields': 'list[CustomFieldDetailed]',
        'groups': 'list[Group]',
        'search_by_distance_data': 'SearchByDistanceData'
    }

    attribute_map = {
        'allow_keywords': 'allowKeywords',
        'fields_in_search': 'fieldsInSearch',
        'address_fields_in_search': 'addressFieldsInSearch',
        'basic_fields': 'basicFields',
        'custom_fields': 'customFields',
        'groups': 'groups',
        'search_by_distance_data': 'searchByDistanceData'
    }

    def __init__(self, allow_keywords=None, fields_in_search=None, address_fields_in_search=None, basic_fields=None, custom_fields=None, groups=None, search_by_distance_data=None, _configuration=None):  # noqa: E501
        """BaseUserDataForSearch - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._allow_keywords = None
        self._fields_in_search = None
        self._address_fields_in_search = None
        self._basic_fields = None
        self._custom_fields = None
        self._groups = None
        self._search_by_distance_data = None
        self.discriminator = None

        if allow_keywords is not None:
            self.allow_keywords = allow_keywords
        if fields_in_search is not None:
            self.fields_in_search = fields_in_search
        if address_fields_in_search is not None:
            self.address_fields_in_search = address_fields_in_search
        if basic_fields is not None:
            self.basic_fields = basic_fields
        if custom_fields is not None:
            self.custom_fields = custom_fields
        if groups is not None:
            self.groups = groups
        if search_by_distance_data is not None:
            self.search_by_distance_data = search_by_distance_data

    @property
    def allow_keywords(self):
        """Gets the allow_keywords of this BaseUserDataForSearch.  # noqa: E501

        Indicates whether using keywords is allowed  # noqa: E501

        :return: The allow_keywords of this BaseUserDataForSearch.  # noqa: E501
        :rtype: bool
        """
        return self._allow_keywords

    @allow_keywords.setter
    def allow_keywords(self, allow_keywords):
        """Sets the allow_keywords of this BaseUserDataForSearch.

        Indicates whether using keywords is allowed  # noqa: E501

        :param allow_keywords: The allow_keywords of this BaseUserDataForSearch.  # noqa: E501
        :type: bool
        """

        self._allow_keywords = allow_keywords

    @property
    def fields_in_search(self):
        """Gets the fields_in_search of this BaseUserDataForSearch.  # noqa: E501

        The internal names of either basic or custom profile fields which  can be used as search filters (separated fields, not keywords)    # noqa: E501

        :return: The fields_in_search of this BaseUserDataForSearch.  # noqa: E501
        :rtype: list[str]
        """
        return self._fields_in_search

    @fields_in_search.setter
    def fields_in_search(self, fields_in_search):
        """Sets the fields_in_search of this BaseUserDataForSearch.

        The internal names of either basic or custom profile fields which  can be used as search filters (separated fields, not keywords)    # noqa: E501

        :param fields_in_search: The fields_in_search of this BaseUserDataForSearch.  # noqa: E501
        :type: list[str]
        """

        self._fields_in_search = fields_in_search

    @property
    def address_fields_in_search(self):
        """Gets the address_fields_in_search of this BaseUserDataForSearch.  # noqa: E501

        Fields which can be used when filtering by user address, by using the `address.<addressField>` name Possibles values for each array element are: * address: Filters by any field in the street address: `addressLine1`, `addressLine2`, `street`, `buildingNumber` or `complement`   * city: Filters by city name * country: Filters by country, represented as 2-letter, uppercase, ISO 3166-1 code (exact match) * neighborhood: Filters by neighborhood name  * poBox: Filters by post-office box (exact match) * region: Filters by region or state * zip: Filters by zip (postal) code (exact match)   # noqa: E501

        :return: The address_fields_in_search of this BaseUserDataForSearch.  # noqa: E501
        :rtype: list[AddressQueryFieldEnum]
        """
        return self._address_fields_in_search

    @address_fields_in_search.setter
    def address_fields_in_search(self, address_fields_in_search):
        """Sets the address_fields_in_search of this BaseUserDataForSearch.

        Fields which can be used when filtering by user address, by using the `address.<addressField>` name Possibles values for each array element are: * address: Filters by any field in the street address: `addressLine1`, `addressLine2`, `street`, `buildingNumber` or `complement`   * city: Filters by city name * country: Filters by country, represented as 2-letter, uppercase, ISO 3166-1 code (exact match) * neighborhood: Filters by neighborhood name  * poBox: Filters by post-office box (exact match) * region: Filters by region or state * zip: Filters by zip (postal) code (exact match)   # noqa: E501

        :param address_fields_in_search: The address_fields_in_search of this BaseUserDataForSearch.  # noqa: E501
        :type: list[AddressQueryFieldEnum]
        """

        self._address_fields_in_search = address_fields_in_search

    @property
    def basic_fields(self):
        """Gets the basic_fields of this BaseUserDataForSearch.  # noqa: E501

        The list of basic profile fields that can be used either as search filters (if the internal names are present in the `fieldsInSearch` property) or on the result list (if the internal names are present in the `fieldsInList` property)   # noqa: E501

        :return: The basic_fields of this BaseUserDataForSearch.  # noqa: E501
        :rtype: list[BasicProfileFieldInput]
        """
        return self._basic_fields

    @basic_fields.setter
    def basic_fields(self, basic_fields):
        """Sets the basic_fields of this BaseUserDataForSearch.

        The list of basic profile fields that can be used either as search filters (if the internal names are present in the `fieldsInSearch` property) or on the result list (if the internal names are present in the `fieldsInList` property)   # noqa: E501

        :param basic_fields: The basic_fields of this BaseUserDataForSearch.  # noqa: E501
        :type: list[BasicProfileFieldInput]
        """

        self._basic_fields = basic_fields

    @property
    def custom_fields(self):
        """Gets the custom_fields of this BaseUserDataForSearch.  # noqa: E501

        The list of custom profile fields that can be used either as search filters (if the internal names are present in the `fieldsInSearch` property) or on the result list (if the internal names are present in the `fieldsInList` property)   # noqa: E501

        :return: The custom_fields of this BaseUserDataForSearch.  # noqa: E501
        :rtype: list[CustomFieldDetailed]
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields):
        """Sets the custom_fields of this BaseUserDataForSearch.

        The list of custom profile fields that can be used either as search filters (if the internal names are present in the `fieldsInSearch` property) or on the result list (if the internal names are present in the `fieldsInList` property)   # noqa: E501

        :param custom_fields: The custom_fields of this BaseUserDataForSearch.  # noqa: E501
        :type: list[CustomFieldDetailed]
        """

        self._custom_fields = custom_fields

    @property
    def groups(self):
        """Gets the groups of this BaseUserDataForSearch.  # noqa: E501

        The groups the authenticated user can use to filter users. Admins can always filter by groups, while users depend on a permission, which can be to only view group sets, only groups or none.   # noqa: E501

        :return: The groups of this BaseUserDataForSearch.  # noqa: E501
        :rtype: list[Group]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this BaseUserDataForSearch.

        The groups the authenticated user can use to filter users. Admins can always filter by groups, while users depend on a permission, which can be to only view group sets, only groups or none.   # noqa: E501

        :param groups: The groups of this BaseUserDataForSearch.  # noqa: E501
        :type: list[Group]
        """

        self._groups = groups

    @property
    def search_by_distance_data(self):
        """Gets the search_by_distance_data of this BaseUserDataForSearch.  # noqa: E501

        Data for searching users by distance  # noqa: E501

        :return: The search_by_distance_data of this BaseUserDataForSearch.  # noqa: E501
        :rtype: SearchByDistanceData
        """
        return self._search_by_distance_data

    @search_by_distance_data.setter
    def search_by_distance_data(self, search_by_distance_data):
        """Sets the search_by_distance_data of this BaseUserDataForSearch.

        Data for searching users by distance  # noqa: E501

        :param search_by_distance_data: The search_by_distance_data of this BaseUserDataForSearch.  # noqa: E501
        :type: SearchByDistanceData
        """

        self._search_by_distance_data = search_by_distance_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BaseUserDataForSearch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BaseUserDataForSearch):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BaseUserDataForSearch):
            return True

        return self.to_dict() != other.to_dict()
