# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class CaptchaResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'challenge': 'str',
        'response': 'str'
    }

    attribute_map = {
        'challenge': 'challenge',
        'response': 'response'
    }

    def __init__(self, challenge=None, response=None, _configuration=None):  # noqa: E501
        """CaptchaResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._challenge = None
        self._response = None
        self.discriminator = None

        if challenge is not None:
            self.challenge = challenge
        if response is not None:
            self.response = response

    @property
    def challenge(self):
        """Gets the challenge of this CaptchaResponse.  # noqa: E501

        The captcha challenge identifier  # noqa: E501

        :return: The challenge of this CaptchaResponse.  # noqa: E501
        :rtype: str
        """
        return self._challenge

    @challenge.setter
    def challenge(self, challenge):
        """Sets the challenge of this CaptchaResponse.

        The captcha challenge identifier  # noqa: E501

        :param challenge: The challenge of this CaptchaResponse.  # noqa: E501
        :type: str
        """

        self._challenge = challenge

    @property
    def response(self):
        """Gets the response of this CaptchaResponse.  # noqa: E501

        The captcha response, as informed by the user  # noqa: E501

        :return: The response of this CaptchaResponse.  # noqa: E501
        :rtype: str
        """
        return self._response

    @response.setter
    def response(self, response):
        """Sets the response of this CaptchaResponse.

        The captcha response, as informed by the user  # noqa: E501

        :param response: The response of this CaptchaResponse.  # noqa: E501
        :type: str
        """

        self._response = response

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CaptchaResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CaptchaResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CaptchaResponse):
            return True

        return self.to_dict() != other.to_dict()
