# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ContactDataForNew(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'contact': 'ContactNew'
    }

    attribute_map = {
        'contact': 'contact'
    }

    def __init__(self, contact=None, _configuration=None):  # noqa: E501
        """ContactDataForNew - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._contact = None
        self.discriminator = None

        if contact is not None:
            self.contact = contact

    @property
    def contact(self):
        """Gets the contact of this ContactDataForNew.  # noqa: E501

        The contact populated with the default fields. This value can be modified and sent back to `POST /{owner}/contacts/{contactUser}`.   # noqa: E501

        :return: The contact of this ContactDataForNew.  # noqa: E501
        :rtype: ContactNew
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this ContactDataForNew.

        The contact populated with the default fields. This value can be modified and sent back to `POST /{owner}/contacts/{contactUser}`.   # noqa: E501

        :param contact: The contact of this ContactDataForNew.  # noqa: E501
        :type: ContactNew
        """

        self._contact = contact

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContactDataForNew, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContactDataForNew):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ContactDataForNew):
            return True

        return self.to_dict() != other.to_dict()
