# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class OrderDataForSetDeliveryMethod(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'currency': 'Currency',
        'delivery_methods': 'list[AdDeliveryMethod]'
    }

    attribute_map = {
        'currency': 'currency',
        'delivery_methods': 'deliveryMethods'
    }

    def __init__(self, currency=None, delivery_methods=None, _configuration=None):  # noqa: E501
        """OrderDataForSetDeliveryMethod - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._currency = None
        self._delivery_methods = None
        self.discriminator = None

        if currency is not None:
            self.currency = currency
        if delivery_methods is not None:
            self.delivery_methods = delivery_methods

    @property
    def currency(self):
        """Gets the currency of this OrderDataForSetDeliveryMethod.  # noqa: E501

        The order currency.  # noqa: E501

        :return: The currency of this OrderDataForSetDeliveryMethod.  # noqa: E501
        :rtype: Currency
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this OrderDataForSetDeliveryMethod.

        The order currency.  # noqa: E501

        :param currency: The currency of this OrderDataForSetDeliveryMethod.  # noqa: E501
        :type: Currency
        """

        self._currency = currency

    @property
    def delivery_methods(self):
        """Gets the delivery_methods of this OrderDataForSetDeliveryMethod.  # noqa: E501

        List with all delivery methods shared by all products contained in the order.    # noqa: E501

        :return: The delivery_methods of this OrderDataForSetDeliveryMethod.  # noqa: E501
        :rtype: list[AdDeliveryMethod]
        """
        return self._delivery_methods

    @delivery_methods.setter
    def delivery_methods(self, delivery_methods):
        """Sets the delivery_methods of this OrderDataForSetDeliveryMethod.

        List with all delivery methods shared by all products contained in the order.    # noqa: E501

        :param delivery_methods: The delivery_methods of this OrderDataForSetDeliveryMethod.  # noqa: E501
        :type: list[AdDeliveryMethod]
        """

        self._delivery_methods = delivery_methods

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderDataForSetDeliveryMethod, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderDataForSetDeliveryMethod):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrderDataForSetDeliveryMethod):
            return True

        return self.to_dict() != other.to_dict()
