# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class OwnerRecordPermissions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'single_record_id': 'str'
    }

    attribute_map = {
        'count': 'count',
        'single_record_id': 'singleRecordId'
    }

    def __init__(self, count=None, single_record_id=None, _configuration=None):  # noqa: E501
        """OwnerRecordPermissions - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._count = None
        self._single_record_id = None
        self.discriminator = None

        if count is not None:
            self.count = count
        if single_record_id is not None:
            self.single_record_id = single_record_id

    @property
    def count(self):
        """Gets the count of this OwnerRecordPermissions.  # noqa: E501

        The current number of records of this type for this owner  # noqa: E501

        :return: The count of this OwnerRecordPermissions.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this OwnerRecordPermissions.

        The current number of records of this type for this owner  # noqa: E501

        :param count: The count of this OwnerRecordPermissions.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def single_record_id(self):
        """Gets the single_record_id of this OwnerRecordPermissions.  # noqa: E501

        If this record type layout is single, and the record exists, contains its identifier   # noqa: E501

        :return: The single_record_id of this OwnerRecordPermissions.  # noqa: E501
        :rtype: str
        """
        return self._single_record_id

    @single_record_id.setter
    def single_record_id(self, single_record_id):
        """Sets the single_record_id of this OwnerRecordPermissions.

        If this record type layout is single, and the record exists, contains its identifier   # noqa: E501

        :param single_record_id: The single_record_id of this OwnerRecordPermissions.  # noqa: E501
        :type: str
        """

        self._single_record_id = single_record_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OwnerRecordPermissions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OwnerRecordPermissions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OwnerRecordPermissions):
            return True

        return self.to_dict() != other.to_dict()
