# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class PhoneDataForEdit(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'phone': 'PhoneEdit',
        'edit': 'bool',
        'remove': 'bool'
    }

    attribute_map = {
        'phone': 'phone',
        'edit': 'edit',
        'remove': 'remove'
    }

    def __init__(self, phone=None, edit=None, remove=None, _configuration=None):  # noqa: E501
        """PhoneDataForEdit - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._phone = None
        self._edit = None
        self._remove = None
        self.discriminator = None

        if phone is not None:
            self.phone = phone
        if edit is not None:
            self.edit = edit
        if remove is not None:
            self.remove = remove

    @property
    def phone(self):
        """Gets the phone of this PhoneDataForEdit.  # noqa: E501

        The phone that is being edited. This value can be modified and sent back on `PUT /phones/{id}`.   # noqa: E501

        :return: The phone of this PhoneDataForEdit.  # noqa: E501
        :rtype: PhoneEdit
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this PhoneDataForEdit.

        The phone that is being edited. This value can be modified and sent back on `PUT /phones/{id}`.   # noqa: E501

        :param phone: The phone of this PhoneDataForEdit.  # noqa: E501
        :type: PhoneEdit
        """

        self._phone = phone

    @property
    def edit(self):
        """Gets the edit of this PhoneDataForEdit.  # noqa: E501

        Can the authenticated user edit this phone?  # noqa: E501

        :return: The edit of this PhoneDataForEdit.  # noqa: E501
        :rtype: bool
        """
        return self._edit

    @edit.setter
    def edit(self, edit):
        """Sets the edit of this PhoneDataForEdit.

        Can the authenticated user edit this phone?  # noqa: E501

        :param edit: The edit of this PhoneDataForEdit.  # noqa: E501
        :type: bool
        """

        self._edit = edit

    @property
    def remove(self):
        """Gets the remove of this PhoneDataForEdit.  # noqa: E501

        Can the authenticated user remove this phone?  # noqa: E501

        :return: The remove of this PhoneDataForEdit.  # noqa: E501
        :rtype: bool
        """
        return self._remove

    @remove.setter
    def remove(self, remove):
        """Sets the remove of this PhoneDataForEdit.

        Can the authenticated user remove this phone?  # noqa: E501

        :param remove: The remove of this PhoneDataForEdit.  # noqa: E501
        :type: bool
        """

        self._remove = remove

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PhoneDataForEdit, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PhoneDataForEdit):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PhoneDataForEdit):
            return True

        return self.to_dict() != other.to_dict()
