# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ShoppingCartCheckout(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'delivery_address': 'AddressNew',
        'delivery_method': 'str',
        'payment_type': 'str'
    }

    attribute_map = {
        'delivery_address': 'deliveryAddress',
        'delivery_method': 'deliveryMethod',
        'payment_type': 'paymentType'
    }

    def __init__(self, delivery_address=None, delivery_method=None, payment_type=None, _configuration=None):  # noqa: E501
        """ShoppingCartCheckout - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._delivery_address = None
        self._delivery_method = None
        self._payment_type = None
        self.discriminator = None

        if delivery_address is not None:
            self.delivery_address = delivery_address
        if delivery_method is not None:
            self.delivery_method = delivery_method
        if payment_type is not None:
            self.payment_type = payment_type

    @property
    def delivery_address(self):
        """Gets the delivery_address of this ShoppingCartCheckout.  # noqa: E501

        The address used for delivery in this specific order. The fields `name`, `defaultAddress` and `hidden` are ignored.   # noqa: E501

        :return: The delivery_address of this ShoppingCartCheckout.  # noqa: E501
        :rtype: AddressNew
        """
        return self._delivery_address

    @delivery_address.setter
    def delivery_address(self, delivery_address):
        """Sets the delivery_address of this ShoppingCartCheckout.

        The address used for delivery in this specific order. The fields `name`, `defaultAddress` and `hidden` are ignored.   # noqa: E501

        :param delivery_address: The delivery_address of this ShoppingCartCheckout.  # noqa: E501
        :type: AddressNew
        """

        self._delivery_address = delivery_address

    @property
    def delivery_method(self):
        """Gets the delivery_method of this ShoppingCartCheckout.  # noqa: E501

        The id of the selected delivery method (if any)    # noqa: E501

        :return: The delivery_method of this ShoppingCartCheckout.  # noqa: E501
        :rtype: str
        """
        return self._delivery_method

    @delivery_method.setter
    def delivery_method(self, delivery_method):
        """Sets the delivery_method of this ShoppingCartCheckout.

        The id of the selected delivery method (if any)    # noqa: E501

        :param delivery_method: The delivery_method of this ShoppingCartCheckout.  # noqa: E501
        :type: str
        """

        self._delivery_method = delivery_method

    @property
    def payment_type(self):
        """Gets the payment_type of this ShoppingCartCheckout.  # noqa: E501

        Either the internal name or id of the selected payment type.   # noqa: E501

        :return: The payment_type of this ShoppingCartCheckout.  # noqa: E501
        :rtype: str
        """
        return self._payment_type

    @payment_type.setter
    def payment_type(self, payment_type):
        """Sets the payment_type of this ShoppingCartCheckout.

        Either the internal name or id of the selected payment type.   # noqa: E501

        :param payment_type: The payment_type of this ShoppingCartCheckout.  # noqa: E501
        :type: str
        """

        self._payment_type = payment_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShoppingCartCheckout, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShoppingCartCheckout):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ShoppingCartCheckout):
            return True

        return self.to_dict() != other.to_dict()
