# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TransferQueryFilters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'currency': 'str',
        'from_account_type': 'str',
        'to_account_type': 'str'
    }

    attribute_map = {
        'currency': 'currency',
        'from_account_type': 'fromAccountType',
        'to_account_type': 'toAccountType'
    }

    def __init__(self, currency=None, from_account_type=None, to_account_type=None, _configuration=None):  # noqa: E501
        """TransferQueryFilters - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._currency = None
        self._from_account_type = None
        self._to_account_type = None
        self.discriminator = None

        if currency is not None:
            self.currency = currency
        if from_account_type is not None:
            self.from_account_type = from_account_type
        if to_account_type is not None:
            self.to_account_type = to_account_type

    @property
    def currency(self):
        """Gets the currency of this TransferQueryFilters.  # noqa: E501

        Either id or internal name of the currency  # noqa: E501

        :return: The currency of this TransferQueryFilters.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this TransferQueryFilters.

        Either id or internal name of the currency  # noqa: E501

        :param currency: The currency of this TransferQueryFilters.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def from_account_type(self):
        """Gets the from_account_type of this TransferQueryFilters.  # noqa: E501

        Either id or internal name of the origin account type  # noqa: E501

        :return: The from_account_type of this TransferQueryFilters.  # noqa: E501
        :rtype: str
        """
        return self._from_account_type

    @from_account_type.setter
    def from_account_type(self, from_account_type):
        """Sets the from_account_type of this TransferQueryFilters.

        Either id or internal name of the origin account type  # noqa: E501

        :param from_account_type: The from_account_type of this TransferQueryFilters.  # noqa: E501
        :type: str
        """

        self._from_account_type = from_account_type

    @property
    def to_account_type(self):
        """Gets the to_account_type of this TransferQueryFilters.  # noqa: E501

        Either id or internal name of the destination account type  # noqa: E501

        :return: The to_account_type of this TransferQueryFilters.  # noqa: E501
        :rtype: str
        """
        return self._to_account_type

    @to_account_type.setter
    def to_account_type(self, to_account_type):
        """Sets the to_account_type of this TransferQueryFilters.

        Either id or internal name of the destination account type  # noqa: E501

        :param to_account_type: The to_account_type of this TransferQueryFilters.  # noqa: E501
        :type: str
        """

        self._to_account_type = to_account_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransferQueryFilters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransferQueryFilters):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TransferQueryFilters):
            return True

        return self.to_dict() != other.to_dict()
