# coding: utf-8

"""
    Cyclos 4.11.5 API

    The REST API for Cyclos 4.11.5  # noqa: E501

    OpenAPI spec version: 4.11.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class VoucherDataForRedeem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'token': 'str',
        'amount': 'BigDecimal',
        'buyer': 'User'
    }

    attribute_map = {
        'token': 'token',
        'amount': 'amount',
        'buyer': 'buyer'
    }

    def __init__(self, token=None, amount=None, buyer=None, _configuration=None):  # noqa: E501
        """VoucherDataForRedeem - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._token = None
        self._amount = None
        self._buyer = None
        self.discriminator = None

        if token is not None:
            self.token = token
        if amount is not None:
            self.amount = amount
        if buyer is not None:
            self.buyer = buyer

    @property
    def token(self):
        """Gets the token of this VoucherDataForRedeem.  # noqa: E501

        The formatted voucher token  # noqa: E501

        :return: The token of this VoucherDataForRedeem.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this VoucherDataForRedeem.

        The formatted voucher token  # noqa: E501

        :param token: The token of this VoucherDataForRedeem.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def amount(self):
        """Gets the amount of this VoucherDataForRedeem.  # noqa: E501

        The voucher amount  # noqa: E501

        :return: The amount of this VoucherDataForRedeem.  # noqa: E501
        :rtype: BigDecimal
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this VoucherDataForRedeem.

        The voucher amount  # noqa: E501

        :param amount: The amount of this VoucherDataForRedeem.  # noqa: E501
        :type: BigDecimal
        """

        self._amount = amount

    @property
    def buyer(self):
        """Gets the buyer of this VoucherDataForRedeem.  # noqa: E501

        The voucher buyer, if any and visible  # noqa: E501

        :return: The buyer of this VoucherDataForRedeem.  # noqa: E501
        :rtype: User
        """
        return self._buyer

    @buyer.setter
    def buyer(self, buyer):
        """Sets the buyer of this VoucherDataForRedeem.

        The voucher buyer, if any and visible  # noqa: E501

        :param buyer: The buyer of this VoucherDataForRedeem.  # noqa: E501
        :type: User
        """

        self._buyer = buyer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VoucherDataForRedeem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VoucherDataForRedeem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VoucherDataForRedeem):
            return True

        return self.to_dict() != other.to_dict()
